# Generated by Django 5.1.1 on 2025-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_feedback_registerform_studentdetails_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherstu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
            ],
        ),
    ]
