# Generated by Django 5.1.1 on 2025-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
